language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
  - julia: nightly
after_success:
  - julia -e 'cd(Pkg.dir("CSTParser")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
